<?php

/**
 * Implementation of template_preprocess_views_view_field().
 *
 * For views to select exiting content, rewrite the nid field ("select" link)
 * to link to the correct target url and pass through the querystring params.
 */
function content_symlinks_preprocess_views_view_field(&$vars) {
  $view = &$vars['view'];
  $field = &$vars['field'];
  $selection_view = explode(':', variable_get('content_menu_add_existing_content_view', 'menu_existing_content_selection'));
  if (($field->field == 'nid') && ($view->name == $selection_view[0]) && ((!isset($selection_view[1]) || ($view->current_display == $selection_view[1])))) {
    module_load_include('inc', 'content_menu', 'content_menu.menu_admin');
    $item = content_menu_get_menu_item_from_querystring();
    $item['link_path'] = 'node/' . $field->original_value;
    $url = 'admin/structure/menu/manage/' . $item['name'] . '/add';
    $new_url = 'admin/structure/menu/manage/add_symlinks/'. $field->original_value;
    $vars['output'] = l(t('select'), $url, array('query' => content_menu_assemble_query_string($item))) .' | '.
      l(t('Use Symlink'), $new_url, array('query' => content_menu_assemble_query_string($item)));
  }
}

/**
 * Implementation of hook_menu().
 */
function content_symlinks_menu() {
  // Add menu router item for use as target with dummy menu items.
  $items['admin/structure/menu/manage/add_symlinks/%node'] = array(
    'title' => 'Add symlinks for Selected Content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('content_symlinks_add_symlinks_path', 5),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'conent_symlinks.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function content_symlinks_theme() {
  return array(
    'content_symlinks_form_items' => array(
      'render element' => 'form',
      'file' => 'content_symlinks.theme.inc',
    ),
  );
}